export interface WordEntry {
  w: string;   // English word
  z: string;   // Chinese meaning (short)
}

export interface BookDef {
  id: string;
  name: string;
  nameZh: string;
  icon: string;
  color: string;    // CSS color for the book card
  words: WordEntry[];
}

export const BOOKS: BookDef[] = [
  {
    id: 'ielts',
    name: 'IELTS Academic',
    nameZh: '雅思学术',
    icon: '🎓',
    color: '#4A90D9',
    words: [
      { w: 'analyze', z: '分析' },
      { w: 'approach', z: '方法' },
      { w: 'assess', z: '评估' },
      { w: 'authority', z: '权威' },
      { w: 'concept', z: '概念' },
      { w: 'constitute', z: '构成' },
      { w: 'context', z: '语境' },
      { w: 'derive', z: '源于' },
      { w: 'distribute', z: '分配' },
      { w: 'environment', z: '环境' },
      { w: 'establish', z: '建立' },
      { w: 'estimate', z: '估计' },
      { w: 'evident', z: '明显的' },
      { w: 'factor', z: '因素' },
      { w: 'formula', z: '公式' },
      { w: 'function', z: '功能' },
      { w: 'identify', z: '识别' },
      { w: 'indicate', z: '表明' },
      { w: 'individual', z: '个人' },
      { w: 'interpret', z: '解释' },
      { w: 'involve', z: '涉及' },
      { w: 'issue', z: '问题' },
      { w: 'legislate', z: '立法' },
      { w: 'method', z: '方法' },
      { w: 'occur', z: '发生' },
      { w: 'percent', z: '百分比' },
      { w: 'period', z: '时期' },
      { w: 'policy', z: '政策' },
      { w: 'principle', z: '原则' },
      { w: 'proceed', z: '继续' },
      { w: 'process', z: '过程' },
      { w: 'require', z: '需要' },
      { w: 'research', z: '研究' },
      { w: 'respond', z: '回应' },
      { w: 'role', z: '角色' },
      { w: 'section', z: '部分' },
      { w: 'significant', z: '重大的' },
      { w: 'similar', z: '相似的' },
      { w: 'source', z: '来源' },
      { w: 'specific', z: '具体的' },
      { w: 'structure', z: '结构' },
      { w: 'theory', z: '理论' },
      { w: 'vary', z: '变化' },
      { w: 'achieve', z: '实现' },
      { w: 'adequate', z: '充足的' },
      { w: 'apparent', z: '显然的' },
      { w: 'appropriate', z: '适当的' },
      { w: 'attribute', z: '归因于' },
      { w: 'benefit', z: '益处' },
      { w: 'create', z: '创造' },
    ],
  },
  {
    id: 'toefl',
    name: 'TOEFL',
    nameZh: '托福',
    icon: '📘',
    color: '#5B8DEF',
    words: [
      { w: 'abandon', z: '放弃' },
      { w: 'absorb', z: '吸收' },
      { w: 'abstract', z: '抽象的' },
      { w: 'accommodate', z: '容纳' },
      { w: 'accomplish', z: '完成' },
      { w: 'accumulate', z: '积累' },
      { w: 'acknowledge', z: '承认' },
      { w: 'adjacent', z: '邻近的' },
      { w: 'advocate', z: '提倡' },
      { w: 'ambiguous', z: '模糊的' },
      { w: 'anticipate', z: '预期' },
      { w: 'apparatus', z: '装置' },
      { w: 'arbitrary', z: '任意的' },
      { w: 'authentic', z: '真实的' },
      { w: 'cease', z: '停止' },
      { w: 'chronic', z: '慢性的' },
      { w: 'circulate', z: '流通' },
      { w: 'commodity', z: '商品' },
      { w: 'compensate', z: '补偿' },
      { w: 'comprehensive', z: '全面的' },
      { w: 'compulsory', z: '强制的' },
      { w: 'conceive', z: '构想' },
      { w: 'confine', z: '限制' },
      { w: 'consequence', z: '后果' },
      { w: 'consistent', z: '一致的' },
      { w: 'constraint', z: '约束' },
      { w: 'contemporary', z: '当代的' },
      { w: 'contradictory', z: '矛盾的' },
      { w: 'controversy', z: '争议' },
      { w: 'convert', z: '转换' },
      { w: 'convey', z: '传达' },
      { w: 'crucial', z: '关键的' },
      { w: 'cumulative', z: '累积的' },
      { w: 'decay', z: '衰退' },
      { w: 'decline', z: '下降' },
      { w: 'deduce', z: '推断' },
      { w: 'demonstrate', z: '证明' },
      { w: 'depict', z: '描绘' },
      { w: 'deplete', z: '耗尽' },
      { w: 'derive', z: '获得' },
      { w: 'detect', z: '探测' },
      { w: 'diminish', z: '减少' },
      { w: 'distinct', z: '不同的' },
      { w: 'diverse', z: '多样的' },
      { w: 'dominant', z: '主导的' },
      { w: 'elaborate', z: '详尽的' },
      { w: 'eliminate', z: '消除' },
      { w: 'embrace', z: '拥抱' },
      { w: 'empirical', z: '经验的' },
      { w: 'encounter', z: '遭遇' },
    ],
  },
  {
    id: 'gre',
    name: 'GRE',
    nameZh: 'GRE',
    icon: '🏛️',
    color: '#8B5CF6',
    words: [
      { w: 'aberrant', z: '异常的' },
      { w: 'abjure', z: '发誓放弃' },
      { w: 'abscond', z: '潜逃' },
      { w: 'abstain', z: '戒绝' },
      { w: 'abstruse', z: '深奥的' },
      { w: 'acerbic', z: '尖刻的' },
      { w: 'acquiesce', z: '默许' },
      { w: 'acrimony', z: '尖刻' },
      { w: 'admonish', z: '告诫' },
      { w: 'adulterate', z: '掺假' },
      { w: 'affable', z: '和蔼的' },
      { w: 'alacrity', z: '敏捷' },
      { w: 'amalgamate', z: '合并' },
      { w: 'ambivalent', z: '矛盾的' },
      { w: 'ameliorate', z: '改善' },
      { w: 'anachronism', z: '时代错误' },
      { w: 'anomaly', z: '异常' },
      { w: 'antipathy', z: '反感' },
      { w: 'apathy', z: '冷漠' },
      { w: 'appease', z: '安抚' },
      { w: 'arcane', z: '神秘的' },
      { w: 'arduous', z: '艰巨的' },
      { w: 'ascetic', z: '苦行的' },
      { w: 'assiduous', z: '勤勉的' },
      { w: 'astute', z: '精明的' },
      { w: 'audacious', z: '大胆的' },
      { w: 'austere', z: '朴素的' },
      { w: 'banal', z: '平庸的' },
      { w: 'belligerent', z: '好斗的' },
      { w: 'benevolent', z: '仁慈的' },
      { w: 'bombastic', z: '夸大的' },
      { w: 'cajole', z: '哄骗' },
      { w: 'candid', z: '坦率的' },
      { w: 'capricious', z: '善变的' },
      { w: 'censure', z: '谴责' },
      { w: 'cogent', z: '有说服力' },
      { w: 'complacent', z: '自满的' },
      { w: 'convoluted', z: '复杂的' },
      { w: 'copious', z: '丰富的' },
      { w: 'corroborate', z: '证实' },
      { w: 'credulous', z: '轻信的' },
      { w: 'dearth', z: '缺乏' },
      { w: 'debunk', z: '揭穿' },
      { w: 'decorum', z: '礼仪' },
      { w: 'deference', z: '尊重' },
      { w: 'deleterious', z: '有害的' },
      { w: 'delineate', z: '描述' },
      { w: 'denounce', z: '谴责' },
      { w: 'deprecate', z: '反对' },
      { w: 'deride', z: '嘲笑' },
    ],
  },
  {
    id: 'cet4',
    name: 'CET-4',
    nameZh: '四级',
    icon: '📗',
    color: '#10B981',
    words: [
      { w: 'ability', z: '能力' },
      { w: 'abroad', z: '在国外' },
      { w: 'absent', z: '缺席的' },
      { w: 'accept', z: '接受' },
      { w: 'achieve', z: '实现' },
      { w: 'advantage', z: '优势' },
      { w: 'afford', z: '负担得起' },
      { w: 'announce', z: '宣布' },
      { w: 'anxiety', z: '焦虑' },
      { w: 'appetite', z: '食欲' },
      { w: 'appreciate', z: '欣赏' },
      { w: 'arrange', z: '安排' },
      { w: 'atmosphere', z: '气氛' },
      { w: 'attempt', z: '尝试' },
      { w: 'attitude', z: '态度' },
      { w: 'attract', z: '吸引' },
      { w: 'audience', z: '观众' },
      { w: 'average', z: '平均的' },
      { w: 'avoid', z: '避免' },
      { w: 'balance', z: '平衡' },
      { w: 'bargain', z: '讨价还价' },
      { w: 'behavior', z: '行为' },
      { w: 'belief', z: '信念' },
      { w: 'benefit', z: '益处' },
      { w: 'blame', z: '责备' },
      { w: 'bother', z: '打扰' },
      { w: 'boundary', z: '边界' },
      { w: 'brilliant', z: '杰出的' },
      { w: 'budget', z: '预算' },
      { w: 'burden', z: '负担' },
      { w: 'capable', z: '有能力的' },
      { w: 'capture', z: '捕获' },
      { w: 'career', z: '职业' },
      { w: 'casual', z: '随意的' },
      { w: 'category', z: '类别' },
      { w: 'celebrate', z: '庆祝' },
      { w: 'challenge', z: '挑战' },
      { w: 'character', z: '性格' },
      { w: 'circumstance', z: '情况' },
      { w: 'climate', z: '气候' },
      { w: 'combine', z: '结合' },
      { w: 'comfort', z: '舒适' },
      { w: 'command', z: '命令' },
      { w: 'comment', z: '评论' },
      { w: 'commit', z: '承诺' },
      { w: 'communicate', z: '交流' },
      { w: 'community', z: '社区' },
      { w: 'companion', z: '同伴' },
      { w: 'compare', z: '比较' },
      { w: 'compete', z: '竞争' },
    ],
  },
  {
    id: 'cet6',
    name: 'CET-6',
    nameZh: '六级',
    icon: '📕',
    color: '#F59E0B',
    words: [
      { w: 'abandon', z: '放弃' },
      { w: 'abolish', z: '废除' },
      { w: 'absorb', z: '吸收' },
      { w: 'absurd', z: '荒谬的' },
      { w: 'abundant', z: '丰富的' },
      { w: 'accelerate', z: '加速' },
      { w: 'accomplish', z: '完成' },
      { w: 'accumulate', z: '积累' },
      { w: 'accurate', z: '精确的' },
      { w: 'acknowledge', z: '承认' },
      { w: 'acquaint', z: '使熟悉' },
      { w: 'adequate', z: '足够的' },
      { w: 'adjacent', z: '邻近的' },
      { w: 'administer', z: '管理' },
      { w: 'adolescent', z: '青少年' },
      { w: 'advocate', z: '提倡' },
      { w: 'aggressive', z: '好斗的' },
      { w: 'alienate', z: '疏远' },
      { w: 'allege', z: '声称' },
      { w: 'allocate', z: '分配' },
      { w: 'alter', z: '改变' },
      { w: 'ambiguous', z: '模糊的' },
      { w: 'ample', z: '充足的' },
      { w: 'anonymous', z: '匿名的' },
      { w: 'appoint', z: '任命' },
      { w: 'appraise', z: '评价' },
      { w: 'arbitrary', z: '任意的' },
      { w: 'arrogant', z: '傲慢的' },
      { w: 'articulate', z: '清晰表达' },
      { w: 'assault', z: '攻击' },
      { w: 'assemble', z: '集合' },
      { w: 'assert', z: '断言' },
      { w: 'asset', z: '资产' },
      { w: 'associate', z: '联系' },
      { w: 'assure', z: '保证' },
      { w: 'authentic', z: '真实的' },
      { w: 'authorize', z: '授权' },
      { w: 'avert', z: '避免' },
      { w: 'awkward', z: '尴尬的' },
      { w: 'bankrupt', z: '破产的' },
      { w: 'barrier', z: '障碍' },
      { w: 'bias', z: '偏见' },
      { w: 'blend', z: '混合' },
      { w: 'boast', z: '吹嘘' },
      { w: 'breach', z: '违反' },
      { w: 'breakthrough', z: '突破' },
      { w: 'brisk', z: '轻快的' },
      { w: 'bulletin', z: '公告' },
      { w: 'bureau', z: '局' },
      { w: 'calculate', z: '计算' },
    ],
  },
];

export const getBook = (id: string): BookDef | undefined => BOOKS.find(b => b.id === id);
